server:
  port: 8083


spring:
  #应用名称
  application:
    name: springboot-elasticSearch-8083

  #elasticsearch 配置信息
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 127.0.0.1:9300

  #数据库配置信息
  datasource:
    #type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 12345

    #hikari默认属性
    hikari:
      pool-name: hikariPool #连接池名称
      minimum-idle: 5 #最小连接数
      maximum-pool-size: 10 #连接池最大连接数
      auto-commit: true #自动提交从池中返回的连接
      idle-timeout: 180000  # 空闲连接存活最大时间，默认600000（10分钟）

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect

  #redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    timeout: 1000   #1秒

    #redis-lettuce连接池
    lettuce:
      pool:
        max-idle: 8   #连接池中的最大空闲连接，默认值也是8
        min-idle: 0   # 连接池中的最小空闲连接，默认值也是0
        max-active: 8   # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个lettuce实例，则此时pool的状态为exhausted(耗尽)。
        max-wait: -1    # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出

  #消息队列
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    cache:
      connection:
        #缓存连接模式，默认一个连接，多个channel
        mode: channel
        #多个连接，多个channel
        #mode: connection

    #当客户端使用AMQP协议连接RabbitMQ时,需要指定连接的virtual host;不指定则表示连默认的virtual host为/
    #如 virtual-host: /test
    virtual-host: /



  #当遇到同样名字的时候，是否允许覆盖注册
  main:
    allow-bean-definition-overriding: true








