server:
  port: 6868
eureka:
  instance:
    hostname: eureka6868.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #是否将自己注册到Eureka服务中，本身就是所有无需注册
    fetch-registry: false #是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址(单机版本配置为: defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ )
      defaultZone: http://eureka6869.com:6869/eureka/,http://eureka6870.com:6870/eureka/