server:
  port: 8989

spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: MYSQL
    generate-ddl: false
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false

  freemarker:
      allow-request-override: false
      allow-session-override: false
      cache: false
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      enabled: true
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: false
      prefer-file-system-access: true
      suffix: .ftl
      template-loader-path: classpath:/templates/
      settings:
        template_update_delay: 0
        default_encoding: UTF-8
        classic_compatible: true
        date_format: yyyy-MM-dd
        time_format: HH:mm:ss
        datetime_format: yyyy-MM-dd HH:mm:ss

  mail:
    host: smtp.exmail.qq.com
    port: 587
    username: ymbx@cunpiao.com
    password: Ymbx888
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
              enable: true
              required: true
  env:
    pro: false
  http:
    multipart:
      max-file-size: 200Mb
      max-request-size: 200Mb

  ## 微信开放平台的秘钥，做微信分享，登录使用
  wechat:
    appId: wxf7a0c2fb8f37ab2d
    appSecret: bee7e6b60c0709b0fe3a3e1f92dede1d

module:
  code: api
  prefix: HT
  uri:
    login: login
    forbidden: /forbidden
    notFound: /404
    forceExit: /forceExit
  page:
    notFound: core/notFound
    error: core/error
  ajax:
    notFound: core/notFoundAjax
    error: core/errorAjax